version: '3.9'

services:
  web:
    container_name: backend
    restart: always
    build: ./backend
    command: /start.sh
    volumes:
      - ./backend/:/usr/src/app/
    #      - .:/backend/
    #      - .:/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - ./backend/backend/.env
    depends_on:
      - redis

  celery:
    build: ./backend
    command: /start-celeryworker.sh
    volumes:
      - ./backend/:/usr/src/app
    env_file:
      - ./backend/backend/.env
    depends_on:
      - web

  celery-beat:
    build: ./backend
    command: /start-celerybeat.sh
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./backend/backend/.env
    depends_on:
      - web

  flower:
    build: ./backend
    command: /start-flower.sh
    ports:
      - "5555:5555"
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./backend/backend/.env
    depends_on:
      - celery
      - celery-beat

  redis:
    image: redis:latest

volumes:
  certs:
  html:
  vhost:
  acme:
